language: ruby
rvm:
- 2.1.1
bundler_args: --without kitchen_vagrant
before_install:
- echo -n $EC2_SSH_KEY_CHUNK_{0..25} >> ~/.ssh/id_ec2.base64
- cat ~/.ssh/id_ec2.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_ec2
- gem install bundler --pre
script:
- bundle exec rake travis
after_script: 
- bundle exec kitchen destroy
env:
  global:
  - EC2_SSH_KEY_PATH="$HOME/.ssh/id_ec2"
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: r9YZxNDmbnwxpAUZLVsFE3CueE7ecdQTlSAu0iuVIpem80Eg9lf54Kve5toDqApHgRgAE5QopZzUqNPFXxURY+TdOTJ6ebMhesiip/VZbOvt3GpKlmVVrFOnCqdxxC7WbTrNNIA+wjPH6l2yjI/gdhl+B9WRIDE0OtcJuQcoAJ0=
  - secure: oxFaFWGevoVJgD8AoBwrZAwlSw/BSl7GG0U2gE6KXxmwbrNOuqnrG3JZ0V8pJLt5ZERovOI9Bo3oSW26FxiqeO/7CWVFJycYk9QfMpk3UYhTTVkQ5MtsWL738pY+YC/v/nHbFw4B38sHdzJQ5z32OpPQcXIzD1uA8h1t9+ttSEQ=
  - secure: VQZExQ1qIg4Y/nXb8xKVj9heUF/0xdBlWCwV5UMLpPWF9bVedM3eWFOCLBaQ3CpU1Z9N3l/MxeZnbtHlyzu6J50iX/wz0N8c/TA6Hatb4q2wvcvWB/d0PdkguR+whIDr8c3FYsh+mTfsenlzHBnayi38ykJ/1ngkvud/t70NGOU=
  - secure: OA/xBKcU33wFa6jm75Qe5oM1wExG6az0TQNluGaEDKmHAMWa58K+zao0K7HJcFpv/rwX/z+7npJsLQGe7VQeIuP1BknYv155TbFG+12V2kWJv7I5VqL/E+ZlBr+SbcPSPLhINaxlygnAbrvtgMlB1rylScGhPoQBZuOC5Jv9cAg=
  - secure: lM0imwB+z4whFaHc/gSJzIldxboHtJtZ1O9Ssjagmxx8fNfwzoi0iwiaVIWIzUaz0rcFyGdH+ddqldSlTY9OPRTtkMZVmtaHDLsQzX80vhOIUbimBtVbT+SLKrYHKVL0o1wOg0cQ/OxbGPvak4NKW58tgGLyUrmt++JJIoM+yVI=
  - secure: D7GNOC0T0U+iVvdAlMuLpLH6bW289XT9ssFAMOfPaVTmgQ+K0R5Q6UK6g6F+hx/n0WL+DACH75N+4Yk4nx1ERqMZBv+fMitGmPCjEop3Wn/muVs5+/NhdCyfj06qMOBlVruccYvce1yfrE7C1Yjwwh7s0dmzm5/QAmjRLsjYx0w=
  - secure: uRjtcXLMFlFf033ZkIOMTc7Dg3T0QoIdhxHNhJi9wNuzrjvIDPugNA45Jm9Fnr8Q4gY5/EnR+pOXSi2riVdndUwRQfAlQxq+JD1/cJ5yk53wIEvheTk6Gorg//t+GQ46WnD70ph2H2h9Z+wDyO2jHUyGNctYDcMeTdvN+6qTMds=
  - secure: v/zb3kE4DQWiok1DcQyMvA2vl5YspRJLaXKRoCpe7wkapevq04Lyl1zhgqzz20POIcu12YEGpJx+sFOcrTVLdg0voRspX/SVq8SjPIU/TY8cZMeAW0gmQxD2guTtDyxFT0+MXk2PWP/9ip8vwzBfQYNlcKuyxBWgeebzj+d6joA=
  - secure: j4rpYBbvo69njx8fUtR2v7RWUWPVq1jhXDwYzqb0RLLGTgTFRq6YrV8QCyhrRhulhp0OifhP1R81/zfLsK4i4hJcidqsqXelTVrxn0pSFiyWuyQhG9HgMGHXHEym5uXPyKu1SqV/tjPqmTEcry9Ha29RngWE1etDtnQkev0z0Eg=
  - secure: jOgLGSlfPkDpzfFfweV5kM+NRfNLs7jcoKeybpoNV5zsCVLgEuq9EA6lJjgAbYwTPhlaaOugNwxf1cxIBNWQdgH6z+I8TVBkd5qMx5eMrvNPI003Bzs1+DDcB+YZ89J0c2z/kJ0lztRkp9RAhVja8ivrncuEpTKHjrWJcrH8xyA=
  - secure: GozlTmuzj9CZ0s1/lTYtZwrVQKktP9BGsnz55IwA2vxiU/q7KaHpasczcr1pgOexP2xEjwf50UAXWP/1QWDJg6fibQakzKc3vMlpRkz8UDs5UpI3o6nzAO19ljmkqCyObuXQoZiE7AYBEDjJ2sEH1fJr3iVUaG+xO8y3OIltWes=
  - secure: QMC9JXLZXFAtUHJv2Z4bZWuKHrLmqHVJttzq5Nw0hvJd6vzyeM04WI0ErBdg9IO3OpbSWr0EbXyO8DyNywgaeUF+uh96S3XcU8PopyBProp1sw0Jcu3wiE0eDX91gzl0KPtsdXqtrlRoP9uqFqiMi18l1OHMLY1QqEsdDw+snvo=
  - secure: jCGiyLHwMq4lE3Ky1+ObPOENNToIs3j69FKq1ygy/xWAEHUfuJwpktJJ21AQ8zeK4cvX4xsMLhM6HVDa46PGaU/CxYK9GqY7ObV8tPgncPQHJd/DfDJdOO0Vqz/GmgBin470h3iSdA9Lp3sjz4R/1N3D5FYCEvl5LIg5DCSJ6R8=
  - secure: sC0HjL+Wg7ebdAjOM+/Qlkz5FQ9qzVXXIVFE1LnQNtJxhuqQFTA0uHSc5ukhO7UvLHj9SNuCV8bz9MheX8Zd0u6l1MlaxqNacsiV1XXUCGV5whI/9Pe1nTdsS/2uhCgQKLdpq14SDKn0tLfd6dD0LiVXeDAfaQlm8jmEqs7yep4=
  - secure: BwNYynRM5YhP/lBqNNuW16f286Ik7AXrtkbVVltdk109HFEuHeFuhv8+WCM0/TFfc1FprFIJtrklhVynI/QZT9zM7FPwsrAQmB8eQGHcIptV+Ju1N1KZfvkYWsr8eynq2oWJW+UysH7Vsyd4O9L8cYEnW0Dtw8Oli13qESEAOfM=
  - secure: sE/BAD5iDYe053lLrq63IBHzeeajNaCOkYbnVc0KhR9w6627B24oKWD+EQn57LdNK2cxfiAZNOUHYQ9pt4bqzCd0NLrpdTwodXHciBtkjClIxd40QSTcAuTw5sQVXwWWxDjf3/gzkmUxhBihf44xgjqlE7Mm7LYXcXjcFiBo3ic=
  - secure: hwpxSbx/0xqDCtmJmn5fLW84bmBoHm6Paist3M2nhb26yUlZSZAL968y7xQWPV8qhVzaNZkWVkuKhlDRMpCexIEuV0Ou0KuCb9Zfg9EHfhd5mYr+TP2Xs/17PTAZy3lhMWBD4w029zzrI0BDcw9NoLpZ7AaD2LFZ4jsJWivc5ak=
  - secure: JJizEY3VyejH+upOuJA7DQRmP0q/C06nI6WKSeaFFsZQHK8F8mwqAIsXDbQp1Kd7dxZ+CUC+/j0XMqUsXiO6UhMUIuVhJQzFLu3ljBd1BKf0OrAGuNySh3YFlAGYOS32W+uH9JY4ZHgs3u4I2tjovJGBssH9kl9UhMcM/0CSwlQ=
  - secure: J9kFxOF/T2e8zk0ho2z4SlhBWjRn/nklj4uiwUrosqjcUHjjEjNt43P+fTtrErQDqujHhUL76SbzyJW7bvDbjQLLLpUSyBxk/iuKkNfe/pUYOtLX/kY1BMJ856jAmbbadGoGqG1rt6xErqSd1gryw2vmyof0aZsEinlfmNy6qnc=
  - secure: v3k9kvxQiiJHzVMw0C3FSx5Mzl4Y4ycdm+Ys0rBcjxionXNqtSTmXFIYArGKvV0bkG30HzNO1Jv9EKR4f8iI8iBdKBH7rdv31bVvIc+qrs1XckGgcd80Wfknq39OFt2Woe0vSOQjSRRscTwaoeHDa4h05MYj0m04I+K3/a/xkKc=
  - secure: q356cbkSncAwSQSq/RxmtoT3RcVQZaj4uVu+UHEHR0PJNU4LgbW84166zDpqgwkMNNfpC/d8Bg4EXtOnnSyWLnnY0eRdFp7aFzTki+8cKtRpRwr/+/NmYZoZCc1ueJrxLusqdmup+9duSz2lP2PCcmiiGIdJ/0W31odtzfHOdF8=
  - secure: LURlQ0xDTIU6qSEK1+7nZ8pIZ4ihz7oQTbDllJPPbLX5DDqthy0Kjg2oy1fDLmpmx+D+2kRFIekOfPcnH064uzQ/8CNB1oHBo6PALz9uWnhyfTrhnQtPXoNE399RhFrYtZ3uo1P+sDufiKcZWTJiy8PEih3u088+ebU10AcVKxg=
  - secure: wqN+RYvWAms7oIRuoW1d7zP0b0EK5dtrbDkY0xucj9T1zzN7AC1uxx9fo5UkX34m0jkRaUJWfTZaY/uf0PMpHGuPv8y04t95xtefGpg1eEaZeWT7EdLuCeBVi0sp1n7GhNN1jsnJDWJeWdxso2w4DwfgYWI5XsBuPLBYuKoAzHk=
  - secure: ZgerCIVGJpiOFdrWKXTOciOn3uL6tFSfexNcDcCCOj6LZiwcw8A++mNc0dYt1HLzria1/mszJClDMlWFpplxsz8/bJAJNFZU9v8WiJsuTjfvm5A3Cw2sT26wESTn73SaHIq8Ts+FudWGUqH4uEK7UUe7KFMIWRtvuNvWOwB2N4Y=
  - secure: DTNK8LtMr2YTrtEyw1gXLQGuQxtCcfWSu3t/eEv8fzLl3sBTUpl3oxJfXyiC9/XZoq0aTYlX4oNpCv98AyE93ktb4+pWbPIoaP7YlP3RGRJg4uzS09ffHM6JbNzIENbZzIbCb180njkvqdCKYszuSLi4HUcVuZGY9uZcDyKrR7c=
  - secure: YjkEvikIf9YZQ+fyVfdlEEJfDMKQ6vWlTy+RKQE4RxAZx0IHnBQoaLWmStNwZTRAOXqsXRRbFXQE4Ubbqgpw+yODWGvlStD7/iH0u8hg4L0ePCtWwNAoF6cIJ734jE5hOqXzpG9EN6JeCD0Zj69kUnwORu5szqRIK0W+sNDyDzo=
  - secure: o7kWzwntqA35upI7KSL+OxmRjIfjlX1OPqRQaMUGJIx6N0ZZktXbPVaNXNguixEPfziWMN9jXhvht36RrSq6skXjPS2qCAHF7fJ3/JEEMkYvFDOCM6YlHWK2QY0XLaAFc+xHhxDS11ulX5cR+to0xtnzXwQAjU0YzKvSsjZM8TE=
  - secure: dJ8lsa+f2W5K/Dw4+/lHcif2c8AXv1kkg8JbxriMD9578i3JHhMREINi1qUe6u0uyDJuKN89ayH252ZPsDQB3OxJVtaGuuYOwBJBOy+czLSz7Y4OdkdwjfRP3PjNAsbp7+oNQkQvily7AkBk2vBi44KtwLBIeuJeOMGeX9h6BKc=
  - secure: ExxBaElfLLztfB1QhK19HMUoEQI49dEeUd7SXIQqJzWhn9MQlq+1RMsVwHb3J7ZL5n16+6a2Kt7nfQfKrzKmCTSPQ1pgc3bbJNU5nfxhBVlZ49F3b7sOOMoMGocCtjRs6xjWBXM3Y4gAYbRAxKhfqxfO2fCQ6TQmI4hdTnKtzz0=
  - secure: IPO/pDzivkyyqssTq04LFl5d25WsfbnBp3ctt56DBtRoxneELv8nhOcaLLv8Ho8yIxuiV6OpJsZeFyD+r8FcjeqIE3nVcU18htxM0TZZeccVjr4KXGTKJ6A1mivAGikB5tURJKWGR+rDdBFQG1YP2XdbR7/gAHJIkRX4oCz7Gug=
  - secure: IFOpUWJSWbAFj/9Ja/cvmCtGDtc7pEqAG0hinM9MRhC3NfgdW41nzguasig3VPmSecUrqvdP2GVRsjnRlWaf6KFjY+nykb7VP8m2j+8OgdfSqyX/TV3VElG9Lr09puYsgc+zYKgdxYZnUcJqrvlB060scE5PYiEqV4Uw0ebVpIo=
  matrix:
  - KITCHEN_INSTANCE="default-ubuntu-1204"
notifications:
  email:
  - techops@americanhonors.org
